server:
  port: 80
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: class-web
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+08:00
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    charset: UTF-8
    suffix: .ftl
    check-template-location: true
  http:
    encoding:
      charset: UTF-8
      force: true